#YML FILE: text document that contains data formatted using YAML
  #YAML: human readable data format used for data serialization

#config will create a service called api from the Dockerfile
version: '3.8'
#version specifies the file format

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    #used to mount the code into the container
    #important because it allows to update the
    #container when a change to the source code is made
    entrypoint: ['/usr/src/app/entrypoint.sh'] #added an entrypoint
    volumes:
      - .:/usr/src/app
    ports:
      - 5004:5000
    environment:
      #what do these mean?
      - FLASK_ENV=development
      #to load app config for the development environment
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@api-db:5432/api_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@api-db:5432/api_test
    depends_on:
      - api-db
  #Postgres will be available on port 5432 for services running in other containers
  api-db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres